language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: $COMPOSER_OPTIONS="--prefer-lowest"
    - php: 7.0
      env: xdebug="yes"
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: nightly
      env: COMPOSER_OPTIONS="--ignore-platform-reqs"

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "nightly" && "$xdebug" != "yes" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update

install:
  - composer update --prefer-stable $COMPOSER_OPTIONS

script:
  - vendor/bin/phpspec run
