sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.6

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: $COMPOSER_OPTIONS="--prefer-lowest"
    - php: 7.0
      env: xdebug="yes"

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" && "$xdebug" != "yes" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update

install:
  - composer update --prefer-stable $COMPOSER_OPTIONS

script:
  - vendor/bin/phpspec run
